### ISSUE TITLE
Error:TypeError: Cannot find function getValues in object

### ISSUE THREAD

**Issue by astillman** [brucemcpherson/SheetsMore#1]
Thanks for the great start on an incredibly useful bit of functionality.  

I'm trying to implement your example and running into an issue with the  getValues method not being available on the specified range, perhaps because I'm not implementing the a1Range string properly...  I tried referencing it both ways I know how...

function testBruceMcPhersonWay() {
  var ssId = "<spreadsheet ID>";
  var ss = SpreadsheetApp.openById(ssId);
  var sheetName = "FilteredSheet";
  var valuesRange = ss.getSheetByName(sheetName).getDataRange();
  //var a1Range = "'" + sheetName + "'!" + valuesRange.getA1Notation();
  var a1Range = sheetName + "!" + valuesRange.getA1Notation();

  var sMore = new SheetsMore.SheetsMore()
  .setAccessToken(ScriptApp.getOAuthToken())
  .setId(ssId);

  var values = sMore
  .applyFilters()
  .getValues(a1Range)
  .filterValues;
  return values;
}

Will try to dig into your source code to understand why this would be happening, but any pointers would be much appreciated!

**Comment by astillman** [comment]
Was able to fix this myself, but it might be worth updating your example on your Google Site so others have a happier path to victory;)  Here's how it looks with my fixes:

function testBruceMcPhersonWay() {
  var ssId = "<spreadsheetId>";
  var ss = SpreadsheetApp.openById(ssId);
  var sheetName = "FilteredSheet";
  var valuesRange = ss.getSheetByName(sheetName).getDataRange();

  var sMore = new SheetsMore.SheetsMore()
  .setAccessToken(ScriptApp.getOAuthToken())
  .setId(ssId);

  var values = sMore
  .applyFilters()
  .getValues(valuesRange)
  .filteredValues;

  return values;
}

**Comment by brucemcpherson** [comment]
Hi Andrew

thanks for noticing and reporting. The problem was the usual library 101
error - i was using the dev version of the library and completely forgot to
create a new version .. just saved it as version 2.

note that not all of the range of filter tests are yet supported .. about
half of them are right now.

bruce
