### ISSUE TITLE
Not filtering data

### ISSUE THREAD

**Issue by MymsMan** [brucemcpherson/SheetsMore#2]
My first problem with SheetSMore was that the documentation states

> Pass an A1Range as a string for the data against which filter need to be applied

But passing a string range does not appear to work - it actually requires a Range object (which is more useful and consistent with the rest of the API)

When I attempt to retrieve the filtered values it returned my entire data range not just the filtered data.
The filter I was using was a simple select by value choosing one string from the pull down list.

my code is 
`function testEmails() {
  var as = SpreadsheetApp.getActiveSpreadsheet();  
  var edata = as.getSheetByName('EmailSort'); 
  edata.activate();
  var cols = edata.getLastColumn()
  //var data = edata.getRange(500,1,300, cols).getValues();
  //var a1Range = 'EmailSort!' + edata.getDataRange().getA1Notation();
  var range =  edata.getDataRange();
  var a1Range =  edata.getDataRange().getA1Notation();
  var sMore = new SheetsMore.SheetsMore()
  .setAccessToken(ScriptApp.getOAuthToken())
  .setId(SpreadsheetApp.getActiveSpreadsheet().getId())
  .setApplyFilterViews(false);

  var data = sMore
  .applyFilters()
  .getValues(range)
  .filteredValues;

  doSendEmails('no',data)
}`

**Comment by brucemcpherson** [comment]
Yes you are right - it's supposed to be a range. ive updated the write up. However, your code seems to work ok - i just cut it down to the minimum below and ran with some made up data. If you want you can send me your sheet on bruce@mcpher.com to see if there is something special about it.

```
function testEmails() {
  var as = SpreadsheetApp.getActiveSpreadsheet();
  var edata = as.getSheetByName('EmailSort'); 
  var range = edata.getDataRange();

  var sMore = new SheetsMore.SheetsMore()
  .setAccessToken(ScriptApp.getOAuthToken())
  .setId(SpreadsheetApp.getActiveSpreadsheet().getId())
  .setApplyFilterViews(false);

  var data = sMore
  .applyFilters()                // this has been aliased to applyFiltersToData() .. both work
  .getValues(range)
  .filteredValues;

  // data was filtered ok
  Logger.log(data);

  // you can check if filtering is on for this range with this
  Logger.log(sMore.isDataFiltered(range));
}
```

**Comment by MymsMan** [comment]
I hadn't looked at the log before since no exception is thrown  but when I did to see the output of the log calls I saw

> [16-10-25 10:50:16:023 PDT] false
> [16-10-25 10:50:16:192 PDT] {err={
>   "error": {
>     "code": 400,
>     "message": "Client project not found. Please pass a valid project.",
>     "status": "INVALID_ARGUMENT",
>     "details": [
>       {
>         "@type": "type.googleapis.com/google.rpc.Help",
>         "links": [
>           {
>             "description": "Google developer console API key",
>             "url": "https://console.developers.google.com/project/189440921201/apiui/credential"
>           }
>         ]
>       }
>     ]
>   }
> }
> , response={
>   "error": {
>     "code": 400,
>     "message": "Client project not found. Please pass a valid project.",
>     "status": "INVALID_ARGUMENT",
>     "details": [
>       {
>         "@type": "type.googleapis.com/google.rpc.Help",
>         "links": [
>           {
>             "description": "Google developer console API key",
>             "url": "https://console.developers.google.com/project/189440921201/apiui/credential"
>           }
>         ]
>       }
>     ]
>   }
> }
> , success=false}

**Is there another library I need to add to my resources list?**

'''
function testEmails() {
  var as = SpreadsheetApp.getActiveSpreadsheet();  
  var edata = as.getSheetByName('EmailSort'); 
  edata.activate();

  var range =  edata.getDataRange();
  var a1Range =  edata.getDataRange().getA1Notation();
  var sMore = new SheetsMore.SheetsMore()
  .setAccessToken(ScriptApp.getOAuthToken())
  .setId(SpreadsheetApp.getActiveSpreadsheet().getId())
  .setApplyFilterViews(false);

  Logger.log(sMore.isDataFiltered(range));
  var data = sMore
  .applyFilters()
  .getValues(range)
  .filteredValues;

  Logger.log(data);

}
'''

**Comment by brucemcpherson** [comment]
I assume you enabled the sheets API in your project console ?

**Comment by MymsMan** [comment]
> I assume you enabled the sheets API in your project console ? 

Thats it - I thought I had but obviously not - all of my other code manipulating spreadsheets and sending emails works without needing to be enabled in the console.
Perhaps a note in the documentation would help others.

I have one very bizarre remaining problem.
If I filter on email address column it always returns the expected results plus the entries for another email address that is not on the filter list, it always chooses the same additional entry which is not visible in Google Sheets filtered data.

When other text columns are filtered only the expected data is returned and I cant reproduce the problem in a test spreadsheet, Unfortunately my real data is too confidential to share

**Comment by MymsMan** [comment]
> I assume you enabled the sheets API in your project console ? 

Thats it - I thought I had but obviously not - all of my other code manipulating spreadsheets and sending emails works without needing to be enabled in the console.
Perhaps a note in the documentation would help others.

I have one very bizarre remaining problem.
If I filter on email address column it always returns the expected results plus the entries for another email address that is not on the filter list, it always chooses the same additional entry which is not visible in Google Sheets filtered data.

When other text columns are filtered only the expected data is returned and I cant reproduce the problem in a test spreadsheet, Unfortunately my real data is too confidential to share

**Comment by brucemcpherson** [comment]
Updated docs and throw an error if not authorized.
Interesting .. let's see see if we can figure it out, if there's anything special about the one it adds. 
- Is it the first,the last ? does your table start at a1? your filtering start at the same place as your table?
- do you have any other kinds of filtering going on aside from text selection ? (not all the filter condition types are supported yet)

**Comment by MymsMan** [comment]
I have managed to create a test spreadsheet that shows the problem which I have shared with you.

The  problem email is near the middle of the list of emails,
Table has 2K+ rows and 50 columns though most columns have been blanked to remove sensitive info.
Table and filtering are at A1 for entire table
No other filtering applied

**Comment by brucemcpherson** [comment]
The problem was that there was a space at the end of the offending email address in each entry in the sheet. When I removed the space, it worked fine. 

The API  reports hidden values as .. 
"hiddenValues": ["xxx@y.com",

Instead of its actual value of 
"hiddenValues": ["xxx@y.com ",

So since the names don't exactly match, it wasn't considered to be hidden. I'll have to think about whether trailing spaces should be considered as significant, or if whether this is an issue in the API that needs to be reported to Google. For now - avoid trailing spaces.

**Comment by MymsMan** [comment]
Thanks for your assistance,

The API should be consistent in is handling of trailing spaces and either strip them from the data or always return them
